added timing bench and changed node requirements for pricing

diff --git a/egomimic/scripts/aria_process/aria-cluster.yaml b/egomimic/scripts/aria_process/aria-cluster.yaml
--- a/egomimic/scripts/aria_process/aria-cluster.yaml
+++ b/egomimic/scripts/aria_process/aria-cluster.yaml
@@ -8,7 +8,7 @@ provider:
 
 auth:
   ssh_user: ubuntu
-  ssh_private_key: put your ssh key .pem
+  ssh_private_key: ~/.ssh/ryan-mac.pem
 
 max_workers: 50
 idle_timeout_minutes: 10
@@ -17,8 +17,8 @@ available_node_types:
   head_node:
     node_config:
       InstanceType: t3.xlarge
-      ImageId: ami-0def8bb9d7dcec6d0
-      KeyName: your-key
+      ImageId: ami-0b3766455f47e0ec4
+      KeyName: ryan-mac
       SubnetId: subnet-02fbc81414d827515
       SecurityGroupIds: [sg-01cabcd4f45211888]
       IamInstanceProfile:
@@ -32,9 +32,9 @@ available_node_types:
 
   worker_node:
     node_config:
-      InstanceType: c5.18xlarge
-      ImageId: ami-0def8bb9d7dcec6d0
-      KeyName: your-key
+      InstanceType: r6a.2xlarge
+      ImageId: ami-0b3766455f47e0ec4
+      KeyName: ryan-mac
       SubnetId: subnet-02fbc81414d827515
       SecurityGroupIds: [sg-01cabcd4f45211888]
       IamInstanceProfile:
@@ -42,7 +42,7 @@ available_node_types:
       BlockDeviceMappings:
         - DeviceName: /dev/sda1
           Ebs: { VolumeSize: 50 }
-    resources: { CPU: 72 , memory: 155254087680 }
+    resources: { CPU: 8 }
     min_workers: 0
     max_workers: 50
 
@@ -53,11 +53,24 @@ initialization_commands:
   - sudo DEBIAN_FRONTEND=noninteractive apt-get update --fix-missing -yq
   - sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq python3-pip python3-dev git fuse3
   - sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq s3fs
-  - sudo pip3 install --no-input --upgrade ray boto3
   - sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq libgl1 libpq-dev
   - sudo pip3 install --no-input sqlalchemy
+  - sudo pip3 install --no-input -U ray boto3
   - sudo pip3 install --no-input --force-reinstall "psycopg[binary]"
   - pip3 install -U projectaria-tools
+  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq ffmpeg libavcodec-dev libavformat-dev libswscale-dev libx264-dev
+  - pip3 install --no-cache-dir --upgrade opencv-python-headless
+  - |
+      echo "=== Testing FFmpeg installation ==="
+      if command -v ffmpeg >/dev/null 2>&1; then
+        ffmpeg -hide_banner -version | head -n 1
+        echo "[OK] FFmpeg is installed and accessible."
+      else
+        echo "[FAIL] FFmpeg not found in PATH."
+      fi
+      echo "=== FFmpeg test done ==="
+  - pip3 install --user --no-input --force-reinstall "click==8.2.1"
+
 
 setup_commands:
   - sudo mkdir -p /mnt/raw /mnt/processed
@@ -93,14 +106,14 @@ setup_commands:
       fi
 
   - |
-      git -C ~/EgoVerse fetch origin main --quiet || true
-      git -C ~/EgoVerse checkout main -q || true
-      git -C ~/EgoVerse pull --quiet || true
-      git -C ~/EgoVerse submodule update --init --recursive --quiet || true
+      cd ~/EgoVerse || true
+      gt checkout main || true
+      gt sync || true
+      gt submodule update --init --recursive --quiet || true
 
   - |
       (crontab -l 2>/dev/null | grep -v run_aria_conversion.py ; \
        echo 'CRON_TZ=America/New_York'; \
-       echo '0 22 * * * /usr/bin/python3 ~/EgoVerse/egomimic/scripts/aria_process/run_aria_conversion.py --skip-if-done >> ~/aria_conversion.log 2>&1') \
+       echo '0 20 * * * /usr/bin/python3 ~/EgoVerse/egomimic/scripts/aria_process/run_aria_conversion.py --skip-if-done >> ~/aria_conversion.log 2>&1') \
        | crontab - || true
   - crontab -l || true
